version: '3'
services:
  web:
    # stdin_open: true # for windows
    tty: true # alternative for stdin_open 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app